### ISSUE TITLE
Frontend: /formal-model and /ml-model return 404 on page refresh

### ISSUE THREAD

**Issue by epura** [Chreggii/syntax-highlighter#137]
https://user-images.githubusercontent.com/45510898/169820511-37b10589-a991-4c9c-8649-addae5a6957f.mp4

**Comment by olikami** [comment]
This is probably a client routing problem and should be resolved by redirecting all URLs to /

**Comment by nikohlUZH** [comment]
> This is probably a client routing problem and should be resolved by redirecting all URLs to /

Yep, it seems to be a routing problem @olikami . I think this post covers our problem.
https://stackoverflow.com/questions/56213079/404-error-on-page-refresh-with-angular-7-nginx-and-docker

However, I haven't been able to fix this yet. If someone else could also take a look, that would be appreciated.
